import { GetStaticProps } from 'next';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Button } from '@mui/material';
import FilterSidebar from '../src/components/FilterSidebar';
import ProductCard from '../src/components/ProductCard';
import ProductsContainer from '../src/components/ProductsContainer';
import { mockProducts as products } from '../src/__mocks__/mockProducts';
import homeStyles from '../styles/Home.module.css';

const Home: NextPage = () => {
	const navItems = [
		{ name: 'Log', link: '/log' },
		{ name: 'Cart', link: '/cart' },
	];

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<>
				{/* This is for ignore nav component padding */}
				<Box
					sx={{ mt: -2, mx: -5, mb: 2, minHeight: '50vh', background: 'red' }}
				>
					Header
				</Box>

				<div className={homeStyles.container}>
					<section className={homeStyles.main}>
						<div style={{ display: 'flex', justifyContent: 'space-between' }}>
							<span>Routes &gt; routes</span>
							<span>Filtros</span>
						</div>

						<ProductsContainer>
							{products.map(product => (
								<ProductCard
									key={product.id}
									product={product}
									type='gallery'
								/>
							))}
						</ProductsContainer>
					</section>
			{/* 		<aside className={homeStyles.sidebar}>
						<FilterSidebar />
					</aside> */}
				</div>
			</>
		</>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async ctx => {
	return {
		props: {
			posts: [],
		},
	};
};
